# Generated by Django 2.1.4 on 2018-12-11 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='summary',
            new_name='summaryy',
        ),
    ]
