# Generated by Django 2.1.4 on 2019-01-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='location',
            field=models.CharField(default='something', max_length=30),
        ),
    ]
